# Generated by Django 4.0.4 on 2022-05-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_checkout_checkoutproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='mode',
            field=models.CharField(default='COD', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic1',
            field=models.ImageField(blank=True, default='noimagep.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic2',
            field=models.ImageField(blank=True, default='noimagep.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic3',
            field=models.ImageField(blank=True, default='noimagep.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic4',
            field=models.ImageField(blank=True, default='noimagep.jpg', null=True, upload_to='images'),
        ),
    ]
