# Generated by Django 4.0.4 on 2022-05-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_checkout_mode_alter_product_pic1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newslater',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
