# Generated by Django 4.0.4 on 2022-05-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_newslater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslater',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
